# Generated by Django 6.0.5 on 2026-06-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=12, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
