# Generated by Django 6.0.5 on 2026-06-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_system', '0002_eventqrcode'),
        ('templates_app', '0003_eventtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqrcode',
            name='event_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='templates_app.eventtemplate'),
        ),
    ]
