# Generated by Django 6.0.5 on 2026-05-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='audio/')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='IzhorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan')], default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.category')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_type', models.CharField(default='color', max_length=20)),
                ('bg_value', models.TextField(blank=True)),
                ('bg_overlay', models.FloatField(default=0.0)),
                ('bg_blur', models.PositiveSmallIntegerField(default=0)),
                ('title_text', models.CharField(blank=True, max_length=300)),
                ('title_font', models.CharField(default='Playfair Display', max_length=100)),
                ('title_size', models.PositiveSmallIntegerField(default=42)),
                ('title_color', models.CharField(default='#ffffff', max_length=20)),
                ('title_effect', models.CharField(default='none', max_length=30)),
                ('message_text', models.TextField(blank=True)),
                ('message_font', models.CharField(default='Crimson Pro', max_length=100)),
                ('message_size', models.PositiveSmallIntegerField(default=18)),
                ('message_color', models.CharField(default='#f0e0e8', max_length=20)),
                ('decorations', models.JSONField(default=list)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_autoplay', models.BooleanField(default=False)),
                ('audio_hidden', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='templates_app.izhortemplate')),
            ],
        ),
    ]
