# Generated by Django 6.0.5 on 2026-06-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('templates_app', '0002_templateconfig_title_font_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', "Nikoh to'yi"), ('osh', 'Osh marosimi')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('couple_names', models.CharField(blank=True, max_length=200)),
                ('invite_text', models.TextField(blank=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=300)),
                ('map_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('meal_type', models.CharField(blank=True, default='Ertalabki osh', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_templates', to='merchants.merchant')),
            ],
        ),
    ]
