# Generated by Django 4.2.30 on 2026-06-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_eventtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='audio_autoplay',
            field=models.BooleanField(default=True),
        ),
    ]
